[profile.default]
src = "contracts"
out = "out"
libs = [
    "lib",
    "node_modules",
]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
hedera_testnet = "https://testnet.hashio.io/api"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
